name: Upload Debug Tpk
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build Debug Apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Running gradle assembleDebug
        run: gradle assembleDebug

      - name: Uploading Debug Tpk and Files
        uses: actions/upload-artifact@v2
        with:
          name: tpk-debug
          path: |
            app/build/outputs/apk/debug
      
